[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "rm -f pnpm-lock.yaml",
    "npm install --legacy-peer-deps",
    "npx playwright install --with-deps chromium"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
